version: '3'

services:

#CLIENTE
    cliente-1:
      build:
          dockerfile: Dockerfile
          context: ./cliente
      container_name: 'cliente-1'
      restart: always
      volumes:
        - /app/node_modules
        - ./cliente:/app
      ports:
        - "8081:3000"
      networks: 
        - app-node-net

#CLIENTE 2
    cliente-2:
      build:
          dockerfile: Dockerfile
          context: ./cliente
      container_name: 'cliente-2'
      restart: always
      volumes:
        - /app/node_modules
        - ./cliente:/app
      ports:
        - "8082:3000"
      networks: 
        - app-node-net  
        
#CLIENTE 3
    cliente-3:
      build:
          dockerfile: Dockerfile
          context: ./cliente
      container_name: 'cliente-3'
      restart: always
      volumes:
        - /app/node_modules
        - ./cliente:/app
      ports:
        - "8083:3000"
      networks: 
        - app-node-net

#BUYER 3
    vendedor:
      build:
          dockerfile: Dockerfile
          context: ./cliente
      container_name: 'vendedor'
      restart: always
      volumes:
        - /app/node_modules
        - ./cliente:/app
      ports:
        - "8084:3000"
      networks: 
        - app-node-net

#SUBASTAS API
    subastas-api:
      build:
          dockerfile: Dockerfile
          context: ./subastas-api
      container_name: 'subastas-api'
      restart: always
      volumes:
        - /app/node_modules
        - ./subastas-api:/app
      ports:
        - "8080:3000"
      networks: 
        - app-node-net

#SUBASTAS 1
    subastas-app-1:
      build: 
        dockerfile: Dockerfile
        context: ./node-app
      container_name: 'subastas-node-app-1-1'
      restart: always
      depends_on:
        - 'subastas-api'
      volumes:
        - /app/node_modules
        - ./node-app:/app
      ports: 
        - "3001:3000"
      environment:
        - CONTAINERS_PATH=subastas-node-app-1-2:3000,subastas-node-app-1-3:3000
        - CONTAINER_NAME=subastas-node-app-1-1
      networks: 
        - app-node-net
    subastas-app-1-2:
      build: 
        dockerfile: Dockerfile
        context: ./node-app
      container_name: 'subastas-node-app-1-2'
      restart: always
      depends_on:
        - 'subastas-api'
      volumes:
        - /app/node_modules
        - ./node-app:/app
      ports: 
        - "3002:3000"
      environment:
        - CONTAINERS_PATH=subastas-node-app-1-1:3000,subastas-node-app-1-3:3000
        - CONTAINER_NAME=subastas-node-app-1-2
      networks: 
        - app-node-net
    subastas-app-1-3:
      build: 
        dockerfile: Dockerfile
        context: ./node-app
      container_name: 'subastas-node-app-1-3'
      restart: always
      depends_on:
        - 'subastas-api'
      volumes:
        - /app/node_modules
        - ./node-app:/app
      ports: 
        - "3003:3000"
      environment:    
        - CONTAINERS_PATH=subastas-node-app-1-1:3000,subastas-node-app-1-2:3000
        - CONTAINER_NAME=subastas-node-app-1-3
      networks: 
        - app-node-net

#SUBASTAS 2
    subastas-app-2:
      build: 
        dockerfile: Dockerfile
        context: ./node-app
      container_name: 'subastas-node-app-2-1'
      restart: always
      depends_on:
        - 'subastas-api'
      volumes:
        - /app/node_modules
        - ./node-app:/app
      ports: 
        - "4001:3000"
      environment:
        - CONTAINERS_PATH=subastas-node-app-2-2:3000,subastas-node-app-2-3:3000
        - CONTAINER_NAME=subastas-node-app-2-1
      networks: 
        - app-node-net
    subastas-app-2-2:
      build: 
        dockerfile: Dockerfile
        context: ./node-app
      container_name: 'subastas-node-app-2-2'
      restart: always
      depends_on:
        - 'subastas-api'
      volumes:
        - /app/node_modules
        - ./node-app:/app
      ports: 
        - "4002:3000"
      environment:
        - CONTAINERS_PATH=subastas-node-app-2-1:3000,subastas-node-app-2-3:3000
        - CONTAINER_NAME=subastas-node-app-2-2
      networks: 
        - app-node-net
    subastas-app-2-3:
      build: 
        dockerfile: Dockerfile
        context: ./node-app
      container_name: 'subastas-node-app-2-3'
      restart: always
      depends_on:
        - 'subastas-api'
      volumes:
        - /app/node_modules
        - ./node-app:/app
      ports: 
        - "4003:3000"
      environment:
        - CONTAINERS_PATH=subastas-node-app-2-2:3000,subastas-node-app-2-1:3000
        - CONTAINER_NAME=subastas-node-app-2-3
      networks: 
        - app-node-net

#SUBASTAS 3
    subastas-app-3-1:
      build: 
        dockerfile: Dockerfile
        context: ./node-app
      container_name: 'subastas-node-app-3-1'
      restart: always
      depends_on:
        - 'subastas-api'
      volumes:
        - /app/node_modules
        - ./node-app:/app
      ports: 
        - "5001:3000"
      environment:
        - CONTAINERS_PATH=subastas-node-app-3-2:3000,subastas-node-app-3-3:3000
        - CONTAINER_NAME=subastas-node-app-3-1
      networks: 
        - app-node-net
    subastas-app-3-2:
      build: 
        dockerfile: Dockerfile
        context: ./node-app
      container_name: 'subastas-node-app-3-2'
      restart: always
      depends_on:
        - 'subastas-api'
      volumes:
        - /app/node_modules
        - ./node-app:/app
      ports: 
        - "5002:3000"
      environment:
        - CONTAINERS_PATH=subastas-node-app-3-1:3000,subastas-node-app-3-3:3000
        - CONTAINER_NAME=subastas-node-app-3-2
      networks: 
        - app-node-net
    subastas-app-3-3:
      build: 
        dockerfile: Dockerfile
        context: ./node-app
      container_name: 'subastas-node-app-3-3'
      restart: always
      depends_on:
        - 'subastas-api'
      volumes:
        - /app/node_modules
        - ./node-app:/app
      ports: 
        - "5003:3000"
      environment:
        - CONTAINERS_PATH=subastas-node-app-3-1:3000,subastas-node-app-3-2:3000
        - CONTAINER_NAME=subastas-node-app-3-3
      networks: 
        - app-node-net
networks: 
  app-node-net:
    driver: 'bridge'

