version: '3'

services:
    subastas-api:
      build:
          dockerfile: Dockerfile
          context: ./subastas-api
      container_name: 'subastas-api'
      restart: always
      volumes:
        - /app/node_modules
        - ./subastas-api:/app
      ports:
        - "8080:3000"
      networks: 
        - app-node-net
    subastas-app-1:
      build: 
        dockerfile: Dockerfile
        context: ./node-app
      container_name: 'subastas-node-app'
      restart: always
      volumes:
        - /app/node_modules
        - ./node-app:/app
      ports: 
        - "3001:3000"
      networks: 
        - app-node-net
    subastas-app-1-2:
      build: 
        dockerfile: Dockerfile
        context: ./node-app
      container_name: 'subastas-node-app-2'
      restart: always
      volumes:
        - /app/node_modules
        - ./node-app:/app
      ports: 
        - "3002:3000"
      networks: 
        - app-node-net
    subastas-app-1-3:
      build: 
        dockerfile: Dockerfile
        context: ./node-app
      container_name: 'subastas-node-app-3'
      restart: always
      volumes:
        - /app/node_modules
        - ./node-app:/app
      ports: 
        - "3003:3000"
      networks: 
        - app-node-net
networks: 
  app-node-net:
    driver: 'bridge'